version: '3.8'
services:

  app:
    build: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=HoangTu
      - POSTGRES_PASSWORD=Anhtu2005@
      - POSTGRES_DB=Database
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: {}
